"""Discovery error code constants."""

DISC_EMPTY_INPUT = "DISC_EMPTY_INPUT"
DISC_UNREADABLE_INPUT = "DISC_UNREADABLE_INPUT"
DISC_UNSUPPORTED_FORMAT = "DISC_UNSUPPORTED_FORMAT"
DISC_PARSE_FAILED = "DISC_PARSE_FAILED"
DISC_PROFILE_BUILD_FAILED = "DISC_PROFILE_BUILD_FAILED"
