"""Error codes for the test harness."""

TEST_CONTRACT_RUN_FAILED = "TEST_CONTRACT_RUN_FAILED"
TEST_ROUNDTRIP_FAILED = "TEST_ROUNDTRIP_FAILED"
TEST_EDGE_GENERATION_FAILED = "TEST_EDGE_GENERATION_FAILED"
TEST_REPORT_WRITE_FAILED = "TEST_REPORT_WRITE_FAILED"
