"""Generator error code constants."""

GEN_RENDER_FAILED = "GEN_RENDER_FAILED"
GEN_SYNTAX_INVALID = "GEN_SYNTAX_INVALID"
GEN_ADAPTER_NOT_FOUND = "GEN_ADAPTER_NOT_FOUND"
GEN_IMPORT_FAILED = "GEN_IMPORT_FAILED"
